--- 
- name: This is my file_variable playbook
  hosts: all
  vars_files: 
    - local.yml

  tasks:
    - name: debug loaded variables
      debug:
        var: URL

    - name: This is my first file variable task  
      debug:
        msg: "{{URL}}"
...
