--- 

- name: Installation of my web-server
  hosts: all
  become: true
  tasks: 
    - name : install web package
      package: 
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"   

    - name : install web package
      package: 
        name: apache2
        state: latest
      when: ansible_os_family == "Debian"   

    - name : install web package
      package: 
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"   

    - name : install web package
      package: 
        name: apache2
        state: started
      when: ansible_os_family == ""Debian""   

...